# Generated by Django 4.2.6 on 2023-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0004_alter_datapoint_added_alter_datapoint_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='title',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
