# Generated by Django 4.2.6 on 2023-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0005_alter_datapoint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='url',
            field=models.URLField(max_length=2255),
        ),
    ]
